### ISSUE TITLE
SOW 2 - Task 2.5:  Standardize PNG and CSVs

### ISSUE THREAD

**Issue by jasmyace** [tmcd82070/CAMP_RST#27]
Standardize the CSV and PNG outputs from the "Estimates production for ALL runs" report so they reflect the same values.

**Comment by jasmyace** [comment]
The impetus for this Task arises from a sequence of emails exchanged between Doug and myself over the summer of 2015.  Via this exchange, Doug questioned why weekly passage estimates for the Spring run, on the American, from 01-Oct-2013 through 29-Sep-2014, disagreed between the `csv` of weekly passage estimates and the `png` of the same.  

Explicitly, given Spring passage results of the following,

![image](https://cloud.githubusercontent.com/assets/9057972/12203780/ed628964-b5ed-11e5-9ead-169820d2f27a.png)

Doug questioned why the `csv` passage estimate for Julian week 8:  Feb. 19 - Feb. 25, for example, displays 3 passage fish, while the `png`, for the same week, displays about 3.5 or so.  

On investigation, it was determined that the differences are due to rounding.  The `csv` passage summary rounds passage to the nearest fish, while the `png` does not.  

To force agreement between the two, within program `run_passage.r`, I made two updates, which are described below.  In the example cited here, current updates display the following.

![image](https://cloud.githubusercontent.com/assets/9057972/12204658/c645a6b8-b5f2-11e5-9431-d60330e51b75.png)


1.  Within the `png`, I rounded the weekly passage estimates to the nearest integer.  This results in agreement with the weekly estimates of the `csv`.  In the examples tested here, the `passage` column of integer fish in the `csv` files and the graphical display in the `png` files agree perfectly.  By "files," I mean comparisons in each of the four seasonal runs for this river and timeframe.  

2.  Within the `csv`, whenever the passage estimate results in zero, I force the `propImputedCatch` to be zero.  While it makes sense statistically why `propImputedCatch` could be non-zero when `passage` is zero, I think a biologist would have an easier time seeing a zero for `propImputedCatch` when the value in the `passage` column is zero.  




Finally, some other things to note:

1.  This update only applies to the `run_passage.r` code, as indicated above.  Practically, this means that the Platform report that estimates passage over lifestage and run requires no update -- this report does not create passage `csv` and `png` files of the type described here.  

2.  The value of total passage reported in the `png` is now directly obtainable by summing the heights of the bars in the corresponding bar-chart `png`.  Specifically, in the river and run described here, "`N=30`" is directly obtainable by summing `3 + 5 + 5 + 6 + 1 + 1 + 7 + 1 + 1 = 30`, where each of the integers in the preceding sum coincides with non-zero passage estimates in the underlying weekly `csv` and bar-heights in the `png`.

3.  This update makes no consideration of the resulting `run_passage_table.csv`.  This is the `csv` that compiles all of the run estimates, along with their confidence intervals.  I don't do any rounding here;  as of now, this means the values here could be off by one or two fish.  Not sure if you realized this impacts this subreport as well.  Let me know if you want me to do something about it.  

4.  For this American timeframe, I put all the pertinent `csv` and `png` files into one Excel workbook.  You should be able to see how the sum of the `passage` column in the `csv` always equals the `N` reported in the `png`.  Note how the values may differ a bit from the `run_passage_table.csv` values.  In statistics, we generally don't ever round until the very end, so given that the `run_passage_table.csv` values are based on sub-calculations involving individual runs, this slight discrepancy is justifiable.  But it could also be changed.  

[AmericanRounding.xlsx](https://github.com/tmcd82070/CAMP_RST/files/83093/AmericanRounding.xlsx)

**Comment by dougthreloff** [comment]
Jason:



Thanks for dealing with task 2.5.  I think you have addressed my concern.



In regards to your bullet 3 below under “Finally, some other things to
note:’  I had not picked up on what you observed.  I can explain the “this
means the values here could be off by one or two fish” to a biologist if
they ask me why the numbers are different.



Doug



*From:* Jason [mailto:notifications@github.com]
*Sent:* Sunday, January 10, 2016 3:43 PM
*To:* tmcd82070/CAMP_RST
*Subject:* Re: [CAMP_RST] SOW 2 - Task 2.5: Standardize PNG and CSVs (#27)



The impetus for this Task arises from a sequence of emails exchanged
between Doug and myself over the summer of 2015. Via this exchange, Doug
questioned why weekly passage estimates for the Spring run, on the
American, from 01-Oct-2013 through 29-Sep-2014, disagreed between the csv
of weekly passage estimates and the png of the same.

Explicitly, given Spring passage results of the following,

[image: Image removed by sender. image]
<https://cloud.githubusercontent.com/assets/9057972/12203780/ed628964-b5ed-11e5-9ead-169820d2f27a.png>

Doug questioned why the csv passage estimate for Julian week 8: Feb. 19 -
Feb. 25, for example, displays 3 passage fish, while the png, for the same
week, displays about 3.5 or so.

On investigation, it was determined that the differences are due to
rounding. The csv passage summary rounds passage to the nearest fish, while
the png does not.

To force agreement between the two, within program run_passage.r, I made
two updates, which are described below. In the example cited here, current
updates display the following.

[image: Image removed by sender. image]
<https://cloud.githubusercontent.com/assets/9057972/12204658/c645a6b8-b5f2-11e5-9431-d60330e51b75.png>

1.     Within the png, I rounded the weekly passage estimates to the
nearest integer. This results in agreement with the weekly estimates of the
csv. In the examples tested here, the passage column of integer fish in the
csv files and the graphical display in the png files agree perfectly. By
"files," I mean comparisons in each of the four seasonal runs for this
river and timeframe.

2.     Within the csv, whenever the passage estimate results in zero, I
force the propImputedCatch to be zero. While it makes sense statistically
why propImputedCatch could be non-zero when passage is zero, I think a
biologist would have an easier time seeing a zero for propImputedCatch when
the value in the passage column is zero.

Finally, some other things to note:

1.     This update only applies to the run_passage.r code, as indicated
above. Practically, this means that the Platform report that estimates
passage over lifestage and run requires no update -- this report does not
create passage csv and png files of the type described here.

2.     The value of total passage reported in the png is now directly
obtainable by summing the heights of the bars in the corresponding
bar-chart png. Specifically, in the river and run described here, "N=30" is
directly obtainable by summing 3 + 5 + 5 + 6 + 1 + 1 + 7 + 1 + 1 = 30,
where each of the integers in the preceding sum coincides with non-zero
passage estimates in the underlying weekly csv and bar-heights in the png.

3.     This update makes no consideration of the resulting
run_passage_table.csv. This is the csv that compiles all of the run
estimates, along with their confidence intervals. I don't do any rounding
here; as of now, this means the values here could be off by one or two
fish. Not sure if you realized this impacts this subreport as well. Let me
know if you want me to do something about it.

4.     For this American timeframe, I put all the pertinent csv and png
files into one Excel workbook. You should be able to see how the sum of the
passage column in the csv always equals the N reported in the png. Note how
the values may differ a bit from the run_passage_table.csv values. In
statistics, we generally don't ever round until the very end, so given that
the run_passage_table.csv values are based on sub-calculations involving
individual runs, this slight discrepancy is justifiable. But it could also
be changed.

AmericanRounding.xlsx
<https://github.com/tmcd82070/CAMP_RST/files/83093/AmericanRounding.xlsx>

—
Reply to this email directly or view it on GitHub
<https://github.com/tmcd82070/CAMP_RST/issues/27#issuecomment-170406562>.[image:
Image removed by sender.]

**Comment by tmcd82070** [comment]
Trent and Jason reviewed, and we think this has been addressed.
