### ISSUE TITLE
SOW 2 - Task 4.1:  Figure out Statistics to Assign Salmon Life Stage

### ISSUE THREAD

**Issue by jasmyace** [tmcd82070/CAMP_RST#40]
Research, develop, and test statistical method(s) to assign juvenile salmon life using fork length and weight data.

**Comment by studyvin** [comment]
I have been using fork length to classify the size class of the fish using mixture distribution. The mixture distribution does not use a predetermined class size. The mixture distribution models the lengths of the fish using the EM algorithm to group the fish and estimate a mean and a variance for each group. 

I have been using data from American river 2015, Clear Creek 2011 and 2012, and Mokelumne 2011 and 2012 to test my modeling approach. In all the datasets the smallest size class is caught a lot more than the other size classes. To overcome this a mixture distribution is fit with only two groups and a sample of the group with the smaller mean is combined with the group with the larger mean. This subset of the data is fit again with a mixture distribution fitting 3 groups. 

The results indicate that the modeling is working well, but in truth it is difficult to assess for certain since the size class assignment is not known. 

My next task is adding covariates into the model. The data I have don't have weights but do have a date of measurement. Initial testing of using the date has resulted in the mixture distribution not converging .

**Comment by jasmyace** [comment]
This task has been completed.  

This does not preclude the possibility that minor changes / updates may have to take place, depending on feedback from Doug and other biologistis.
