### ISSUE TITLE
ALLRUNS production report aborts because one or more temp tables do not exist in the CAMP.mdb.  

### ISSUE THREAD

**Issue by dougthreloff** [tmcd82070/CAMP_RST#46]
the attempt to develop an ALLRUNS production report results in an abort because one or more temp tables do not exist in the CAMP.mdb.  The screen shots below provide the criteria I used as I ran a report and a portion of the R output file with text about the abort.  You can independently replicate this error message by:  (1) downloading a copy of the Battle Creek/Clear Creek CAMP.mdb file from Connie’s Admin FTP site and running an ALLRUNS production report using my criteria, or (2) removing any of the temp tables generated by the R code (i.e., Connie’s SQL).  Connie believes the root cause for this issue may have previously been addressed by Trent such that the absence of the temp datable sin the CAMP.mdb did not cause an abort, but the latest version of the R code has been revised so this issue has reappeared.  

Preventing this error by adding the temp tables into the backend CAMP.mdb may not be the best fix because there could be cases where temp tables are present in a CAMP.mdb, they get cleared by the R code as a report is run, but then some missing data (e.g., trap efficiency data) causes the R code aborts, leaving a CAMP.mdb file that then aborts the next time a new report is run because the R code deleted the temp tables.  

Please give Connie a call and she can provide more background on this issue if you need it.

**Comment by jasmyace** [comment]
[R bugs.docx](https://github.com/tmcd82070/CAMP_RST/files/6008/R.bugs.docx)




[run.passage_CC lower RST_2015-09-29_11-17-22_run_passage_table.xlsx](https://github.com/tmcd82070/CAMP_RST/files/6016/run.passage_CC.lower.RST_2015-09-29_11-17-22_run_passage_table.xlsx)
[R bugs.docx](https://github.com/tmcd82070/CAMP_RST/files/6017/R.bugs.docx)

**Comment by jasmyace** [comment]
[R bugs.docx](https://github.com/tmcd82070/CAMP_RST/files/6034/R.bugs.docx)
[run.passage_CC lower RST_2015-09-29_11-17-22_run_passage_table.xlsx](https://github.com/tmcd82070/CAMP_RST/files/6035/run.passage_CC.lower.RST_2015-09-29_11-17-22_run_passage_table.xlsx)

**Comment by jasmyace** [comment]
As far as I know, bringing databases up-to-date with the current code methodology requires adding a few temp tables.  This is because, via the current querying process, the R code wants to drop these tables before re-inserting them into the database.  This implies that if a temp table is never manually inserted prior to the first run in the current code set-up, it won't work.  But, you know this, because this is exactly what your issue points out.  

The concern is what happens if a database run leads to the breakdown of code somewhere in the middle of a routine, in which a temp table has been deleted by the program?  In this case, the code would stop, and not reinsert the finished temp table -- this means that the next run would have no temp table to delete, leading to yet another error.  I can see where this setup is not ideal, but yet, as far as I know, this is how it's always been done.  This isn't the best excuse to *not* make an improvement, but as far as I know, everything up to know has seemed to hum along as well as can be expected.  While a few bugs here and there lead to code breakdown, which *may* lead to issues involving the temp tables, I like to think these are few and far between.  Said another way, the amount of time and headache to fix (the few) issues that arise due to things being setup as they are now would be less than the amount of time to recalibrate the current querying scenario to some other standard (at least in my opinion).

**Comment by ConnieShannon** [comment]
Jason, I don't think this error occurred before the last round of edits to the R code.  I never put those tables into the back-end databases.  They were created by the R application when the user ran an analyses with the older version of the R application.  This can be tested.  
Trent had some way of either checking to see if the table existed and only dropping if it did, or he handled the exception (in comment or something) and then built the table.  I believe Trent may solve this one.

**Comment by tmcd82070** [comment]
This issue has been with us for a while. It is SQL/Access/ODBC issue. Keep in mind my memory is a little hazy here, so we'll need to dive into this again. 

Inside Access, you can run an CREATE TABLE (or maybe it's UPDATE) query on an existing table no problem.      

When connected to Access via ODBC, you cannot run a CREATE table query on an existing table.  Hence, I insert DROP table queries right before each of Connie's temp table creations.  But, DROP table fails if the table does not exist (as noted).  The solution is to test whether a table exists prior to DROP-ing it.  To my surprize, checking for existance of a table using pure SQL is not straight forward.  I had a solution that worked in some cases, but failed in others, and I eventually lost track of this (because the tables exist most of the time).  

We need to rectify this to make the platform robust.  Jason and I will consult Sara and Bobby (WEST's SQL programmers) and come up with a method.

**Comment by dougthreloff** [comment]
Trent:



Thanks for the update and for working with Jason to rectify the issue.  It
is good West has SQL programmers that can provide advice on how to deal
with the issue.



Doug



*From:* Trent [mailto:notifications@github.com]
*Sent:* Tuesday, October 06, 2015 9:18 AM
*To:* tmcd82070/CAMP_RST
*Cc:* dougthreloff
*Subject:* Re: [CAMP_RST] ALLRUNS production report aborts because one or
more temp tables do not exist in the CAMP.mdb. (#46)



This issue has been with us for a while. It is SQL/Access/ODBC issue. Keep
in mind my memory is a little hazy here, so we'll need to dive into this
again.

Inside Access, you can run an CREATE TABLE (or maybe it's UPDATE) query on
an existing table no problem.

When connected to Access via ODBC, you cannot run a CREATE table query on
an existing table. Hence, I insert DROP table queries right before each of
Connie's temp table creations. But, DROP table fails if the table does not
exist (as noted). The solution is to test whether a table exists prior to
DROP-ing it. To my surprize, checking for existance of a table using pure
SQL is not straight forward. I had a solution that worked in some cases,
but failed in others, and I eventually lost track of this (because the
tables exist most of the time).

We need to rectify this to make the platform robust. Jason and I will
consult Sara and Bobby (WEST's SQL programmers) and come up with a method.

—
Reply to this email directly or view it on GitHub
<https://github.com/tmcd82070/CAMP_RST/issues/46#issuecomment-145917032>.[image:
Image removed by sender.]

**Comment by ConnieShannon** [comment]
Will this work? 

Just issue the DROP TABLE MY_TABLE inside an ignore error wrapper.  If the table exists you will delete it.  If the table doesn't exist you will ignore the error.  

I thought this was the fix Trent had found before.

In an access module it looks like this:
On Error Resume Next
DoCmd.RunSQL "DROP TABLE <TableName>;"
On Error GoTo 0

**Comment by tmcd82070** [comment]
A good thought Connie.  While we are not running an Access module, we have
a similar ignore error wrapper in R.  We will try this.  However, the error
is thrown by the routine that handles our ODBC connection, and I it may not
let us ignore the error.  I get the sneaky feeling that this was the issue
last time (i.e., I thought this would work, but R's equivalent of   RunSQL
does not allow the user to ignore, and I never got around to fixing it
because it happens so rarely).


On Tue, Oct 6, 2015 at 10:58 AM, ConnieShannon <notifications@github.com>
wrote:

> Will this work?
>
> Just issue the DROP TABLE MY_TABLE inside an ignore error wrapper. If the
> table exists you will delete it. If the table doesn't exist you will ignore
> the error.
>
> I thought this was the fix Trent had found before.
>
> In an access module it looks like this:
> On Error Resume Next
> DoCmd.RunSQL "DROP TABLE ;"
> On Error GoTo 0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tmcd82070/CAMP_RST/issues/46#issuecomment-145927490>.
>



-- 
DWH ATTORNEY WORK PRODUCT / ATTORNEY-CLIENT COMMUNICATIONS


*Trent McDonald, PhD *
*Senior Statistician*


Environmental & Statistical Consultants
200 S. Second Street
Laramie, WY 82070
(307) 721-3172
(307) 760-4721 Cell
tmcdonald@west-inc.com
www.west-inc.com

*Follow WEST: *Facebook
<http://www.facebook.com/pages/Western%E2%80%90EcoSystems%E2%80%90Technology%E2%80%90WESTInc/125604770807646>
, Twitter <http://twitter.com/WestEcoSystems>, Linked In
<http://www.linkedin.com/company/1458419>, Join our Mailing list
<http://visitor.r20.constantcontact.com/manage/optin/ea?v=001qrD4A3S5xJ5KgMyelH9jyw%3D%3D>

CONFIDENTIALITY NOTICE:  This message and any accompanying communications
are covered by the Electronic Communications Privacy Act, 18 U.S.C. §§
2510-2521, and contain information that is privileged, confidential or
otherwise protected from disclosure.  If you are not the intended recipient
or an agent responsible for delivering the communication to the intended
recipient, you are hereby notified that you have received this
communication in error.  Dissemination, distribution or copying of this
e-mail or the information herein by anyone other than the intended
recipient, or an employee or agent responsible for delivering the message
to the intended recipient, is prohibited.  If you have received this
communication in error, please notify us immediately by e-mail and delete
the original message.  Thank you.

P Please consider the environment before printing.

**Comment by jasmyace** [comment]
From Doug: 

"Thanks for your call today.  For future reference, this email provides a record of what we 
discussed, so please let me know if I mischaracterized something.  We talked about 2 issues as 
described below.

Issue 1:  The issue of temporary tables being absent from the CAMP.mdb file.  The absence 
of these tables causes the R code to abort

We discussed 3 potential solutions:

**Option A**) having Connie insert the temp tables into any CAMP.mdb files she distributes to the 
field biologists so they are available to the R code when reports are generated.  
The advantages of this solution are: (1) it will take a few minutes to implement, and (2) it 
will not require the expenditure of funds that have been obligated to the West 
subcontract.

The disadvantages of this approach are:  (1) it does not provide a fundamental remedy 
which addresses the R code abort that results when the tables are absent; (2) it will 
require that Connie or I respond to biologist phone calls when this problem arises, and 
she or I will need to interpret the R output files to see if this issue is causing the abort, 
and if it is she or I will then need to provide instruction on how the biologists will 
manually insert the temp tables in their CAMP.mdb; (3) the insertion of the temp tables 
into the CAMP.mdb by Connie could subsequently be undone if the R codes deletes the 
tables and the code then encounters a problem as an R analysis occurs; (4) it could result 
in some frustration on the part of the biologists because they are encountering a situation 
that could be rectified.

**Option B**) Jason would develop R code that causes R to check the CAMP.mdb to make sure the 
temp tables are present in the CAMP.mdb before it attempts to develop a report, and if they are 
absent, R would insert new temp tables in the CAMP.mdb.
The advantages of this solution are:  (1) it would reduce the likelihood that R would abort 
when a report is run.

The disadvantages of this approach are:  (1) it would consume ~ 4 hours of programming 
time to build R code that inserts the temp tables in the CAMP.mdb.

**Option C**) Jason would develop R code that causes R to check the CAMP.mdb to see if the temp 
tables are present and if they are not, R would insert new temp tables.  The R code would also 
check and see if any temp tables were present, and if they were, R code would be developed to 
delete those tables and then insert new blank temp tables in the CAMP.mdb.
The advantages of this solution are:  (1) this approach would result in the optimal 
solution to the issue of missing temp tables.

The disadvantages of this approach are:  it would consume ~ 8 hours of programming 
time to build R code that that alters the CAMP.mdb file in the 2 aforementioned ways.

**Resolution**:  For now, we will adoption Option A, i.e., Connie will insert temp tables into any 
CAMP.mdb files she distributes to the field biologists.  This option was chosen because there 
appears to be a low likelihood that the temp table issue will resurface if Connie inserts the tempt 
table sin the CAMP.mdb, and it will help to save funds that can be used for other West Inc 
activities.  If the field biologists encounter R code aborts that involve the missing temp tables 
more than 2 or 3 times, we will revisit this issue and discuss how we will pursue options b or c."

**Comment by tmcd82070** [comment]
Let's not forget this issue.  If time remains later, let's implement option
B or C.  Alternatively, something simple may occur to us.

*Trent McDonald, PhD *
*Senior Statistician*


Environmental & Statistical Consultants
200 S. Second Street
Laramie, WY 82070
(307) 721-3172
(307) 760-4721 Cell
tmcdonald@west-inc.com
www.west-inc.com

*Follow WEST: *Facebook
<http://www.facebook.com/pages/Western%E2%80%90EcoSystems%E2%80%90Technology%E2%80%90WESTInc/125604770807646>
, Twitter <http://twitter.com/WestEcoSystems>, Linked In
<http://www.linkedin.com/company/1458419>, Join our Mailing list
<http://visitor.r20.constantcontact.com/manage/optin/ea?v=001qrD4A3S5xJ5KgMyelH9jyw%3D%3D>

CONFIDENTIALITY NOTICE:  This message and any accompanying communications
are covered by the Electronic Communications Privacy Act, 18 U.S.C. §§
2510-2521, and contain information that is privileged, confidential or
otherwise protected from disclosure.  If you are not the intended recipient
or an agent responsible for delivering the communication to the intended
recipient, you are hereby notified that you have received this
communication in error.  Dissemination, distribution or copying of this
e-mail or the information herein by anyone other than the intended
recipient, or an employee or agent responsible for delivering the message
to the intended recipient, is prohibited.  If you have received this
communication in error, please notify us immediately by e-mail and delete
the original message.  Thank you.

P Please consider the environment before printing.

**Comment by dougthreloff** [comment]
Thanks for the update and dealing with this issue!



*From:* Jason [mailto:notifications@github.com]
*Sent:* Friday, October 16, 2015 6:18 AM
*To:* tmcd82070/CAMP_RST
*Cc:* dougthreloff
*Subject:* Re: [CAMP_RST] ALLRUNS production report aborts because one or
more temp tables do not exist in the CAMP.mdb. (#46)



Closed #46 <https://github.com/tmcd82070/CAMP_RST/issues/46>.

—
Reply to this email directly or view it on GitHub
<https://github.com/tmcd82070/CAMP_RST/issues/46#event-437518657>.[image:
Image removed by sender.]
