### ISSUE TITLE
POSIX error on fall Daylight Savings Day in 2002

### ISSUE THREAD

**Issue by jasmyace** [tmcd82070/CAMP_RST#57]
When big-looping my attempted update to include Connie's non-valid-fishing periods, as detailed in the issues associated with Tasks 2.8 and 2.9, I came across an error in R program `assign_batch_date.R`.  This program assigns the `batchDate` used in all temporal reports, which is most of them.  It seems to always be equal to variable `SampleDate` in several key catch-specific queries in the Access databases.  So, an error in this program is a cause for concern.  With that said, it's peculiar this error has not popped up before.  This is the type of error that would have caused the Platform to abort.  

This error manifested after using Connie's new query to catch non-valid fishing periods for the river and run detailed below.  I don't think there's any issue with the query; i.e., it's an R problem.  The sequence of code that gets the non-valid fishing is the same as that as the valid fishing.  Also, the big-looper got through 37 different run sequences before finding this particular issue.  So, I think this particular error is peculiar to this particular river and time-frame query.  Said another way, all previous output generated via the Platform is not affected by this error.  

In loop No. 38, which happens to run on the RBDD, siteID 42000, dates 10/1/2002 - 9/30/2003, Spring run, I find that the use of code 

    min.day <- min(df$EndTime) - 24*60*60
    max.day <- max(df$EndTime) + 2*24*60*60
    cut.seq <- seq( min.day, max.day, by=24*60*60 )

on lines `14-16` results in a duplication in the `cut.seq` vector of days, with the duplication happening on October 27, 2002.  Note that the way in which `cut.seq` is defined suggests this should be impossible, as the `24*60*60` syntax suggests that the temporal vector should augment by one day, for each entry.  However, October 27, 2002 was the day clocks were set back in this year, due to Daylight Savings.  So, a possible 23-hour time-space could possibly allow for two entries in vector `cut.seq` to have the same day.  Finally, and this is key, observe that the time zone is not explicitly set in variables `min.day` and `max.day`.  I find, however, that when I explicitly set the time zone, as in 

    min.day <- as.POSIXlt( min(df$EndTime) - 24*60*60, format="%Y-%m-%d %H:%M:%S", tz=time.zone )
    max.day <- as.POSIXlt( max(df$EndTime) + 2*24*60*60, format="%Y-%m-%d %H:%M:%S", tz=time.zone )
    cut.seq <- seq( min.day, max.day, by=24*60*60 ),

the duplication in the vector `cut.seq` disappears, and the code runs as expected, with believable output, for loop run No. 38.  

The code amended above is ubiquitous.  We will need to keep an eye on the eventual final passage output, and compare it with historical runs, in order to make sure this program is continuing to run as expected.  Any possible repercussions in putting variables `min.day` and `max.day` through the `as.POSIXlt` function should be identified now.  

Even though I was able to fix `min.day` and `max.day` in this instance, I will keep this Issue open until we see more evidence that manipuating the functions in `assign_batch_date.R` has no malicious side effects.

**Comment by tmcd82070** [comment]
Daylight saving slips the hour at 2 am.  Technically, on the October day we
set clocks back, the hour between 2 am and 3 am repeats. In spring, when we
go back, the hour between 2 and 3 am on that day does not exist.

Problem was one of the values in cut.seq landed in the duplicated hour of
DST.  Changing time zones changed the values by 6 or 7 hours and moved the
offending value out of the duplicated hour.  While we should always include
the time zone (I thought I had), doing so will not fix this problem for
sure because we can get a value in the duplicated hour in the Pacific time
zone.

Real fix is to make sure min.day (in Pacific time zone) does not have a
time between 2 am and 3 am.  Add this line after min.day is computed, or
better yet, write a new function that is always called when we construct
such date sequences.

_min.day <- as.POSIXct( format(min.day,"%Y-%m-%d"), format="%Y-%m-%d",
tz=time.zone)_

This will move the start of the sequence to midnight (hour 0:0:0) of the
min day.

*-------------------------------------------------------*
*Trent McDonald, PhD *
*Senior Statistician*


Environmental & Statistical Consultants
200 S. Second Street
Laramie, WY 82070
(307) 721-3172
(307) 760-4721 Cell
tmcdonald@west-inc.com
www.west-inc.com

*Follow WEST: *Facebook
<http://www.facebook.com/pages/Western%E2%80%90EcoSystems%E2%80%90Technology%E2%80%90WESTInc/125604770807646>
, Twitter <http://twitter.com/WestEcoSystems>, Linked In
<http://www.linkedin.com/company/1458419>, Join our Mailing list
<http://visitor.r20.constantcontact.com/manage/optin/ea?v=001qrD4A3S5xJ5KgMyelH9jyw%3D%3D>

CONFIDENTIALITY NOTICE:  This message and any accompanying communications
are covered by the Electronic Communications Privacy Act, 18 U.S.C. §§
2510-2521, and contain information that is privileged, confidential or
otherwise protected from disclosure.  If you are not the intended recipient
or an agent responsible for delivering the communication to the intended
recipient, you are hereby notified that you have received this
communication in error.  Dissemination, distribution or copying of this
e-mail or the information herein by anyone other than the intended
recipient, or an employee or agent responsible for delivering the message
to the intended recipient, is prohibited.  If you have received this
communication in error, please notify us immediately by e-mail and delete
the original message.  Thank you.

P Please consider the environment before printing.

**Comment by jasmyace** [comment]
Making the advised change didn't seem to work.  Recall that variable `samplePeriodCutTime` is set in `source_all.R` as `04:00:00`.  The original code looked like

    # original code
    cuttime  <- get( "samplePeriodCutTime", env=.GlobalEnv )
    min.day <- min(df$EndTime) - 24*60*60
    max.day <- max(df$EndTime) + 2*24*60*60
    cut.seq <- seq( min.day, max.day, by=24*60*60 )
    cut.day <- format( cut.seq, "%Y-%m-%d" )
    cut.seq <- as.POSIXct( paste( cut.day, cuttime ), format="%Y-%m-%d %H:%M:%S", tz=time.zone)

First, I tried to manipulate variable `min.day`.

    # try 1
    cuttime  <- get( "samplePeriodCutTime", env=.GlobalEnv )
    min.day  <- min(df$EndTime) - 24*60*60
    min.day2 <- as.POSIXct( format(min.day,"%Y-%m-%d"), format="%Y-%m-%d", tz=time.zone)
    max.day  <- max(df$EndTime) + 2*24*60*60
    cut.seq  <- seq( min.day2, max.day, by=24*60*60 )
    cut.day  <- format( cut.seq, "%Y-%m-%d" )
    cut.seq  <- as.POSIXct( paste( cut.day, cuttime ), format="%Y-%m-%d %H:%M:%S", tz=time.zone)

This failed to remove the duplication on day October 27th.  

I then tried to modify `max.day` in the same way.  

    # try 2
    cuttime  <- get( "samplePeriodCutTime", env=.GlobalEnv )
    min.day  <- min(df$EndTime) - 24*60*60
    min.day2 <- as.POSIXct( format(min.day,"%Y-%m-%d"), format="%Y-%m-%d", tz=time.zone)
    max.day  <- max(df$EndTime) + 2*24*60*60
    max.day2 <- as.POSIXct( format(max.day,"%Y-%m-%d"), format="%Y-%m-%d", tz=time.zone)
    cut.seq  <- seq( min.day2, max.day2, by=24*60*60 )
    cut.day  <- format( cut.seq, "%Y-%m-%d" )
    cut.seq  <- as.POSIXct( paste( cut.day, cuttime ), format="%Y-%m-%d %H:%M:%S", tz=time.zone)

This also didn't work.  

I then tried to set `cuttime` to midnight.

    # try 3
    cuttime  <- "00:00:00"
    min.day  <- min(df$EndTime) - 24*60*60
    min.day2 <- as.POSIXct( format(min.day,"%Y-%m-%d"), format="%Y-%m-%d", tz=time.zone)
    max.day  <- max(df$EndTime) + 2*24*60*60
    max.day2 <- as.POSIXct( format(max.day,"%Y-%m-%d"), format="%Y-%m-%d", tz=time.zone)
    cut.seq  <- seq( min.day2, max.day2, by=24*60*60 )
    cut.day  <- format( cut.seq, "%Y-%m-%d" )
    cut.seq  <- as.POSIXct( paste( cut.day, cuttime ), format="%Y-%m-%d %H:%M:%S", tz=time.zone) 

But, this also didn't work.  At this point, I stopped.  

I saved an `RData` file containing the `time.zone`, `min.date`, `max.date`, and `samplePeriodCutTime` in `"//lar-file-srv/Data/PSMFC_CampRST/ThePlatform/CAMP_RST20151130/Outputs/POSIXError_2016.01.06.RData"`.  There is also an R script (entitled the same) that loads and runs the data and code contained in this issue.  It may be helpful to tinker with the data directly.

**Comment by jasmyace** [comment]
In retrospect, I wonder if simply using the `unique` function to remove the duplicate in `cut.seq` is the easy answer here?   So, 

    cut.seq <- as.POSIXct( paste( cut.day, cuttime ), format="%Y-%m-%d %H:%M:%S", tz=time.zone)

would change to 

    cut.seq <- unique(as.POSIXct( paste( cut.day, cuttime ), format="%Y-%m-%d %H:%M:%S", tz=time.zone)).

This produces output that appears correct.  

![run 38--all_sacramento river_rbdd rst_2002-10-01_2003-09-30_len_freq](https://cloud.githubusercontent.com/assets/9057972/12157075/592d70ea-b48c-11e5-99f1-d6fced2a8e02.png)

**Comment by jasmyace** [comment]
I have checked several different passage runs from the RBDD that cover the date in question (October 27, 2002), and see none for which the underlying baseTables appear to skip a day, or double a day.  I checked a couple of baseTables from each of the ALL Runs report, and the lifeStage report.  

I will now close the issue.
