### ISSUE TITLE
Error When Running the Platform

### ISSUE THREAD

**Issue by jasmyace** [tmcd82070/CAMP_RST#58]
I'm currently receiving an error when attempting to use the Platform.  It was working fine late last week.  This Issue is in tandem with the Issue "General Organization of Current Platform and Its Components," since I think I don't have the most recent version of the Platform, which may function as a practical fix for this problem.  

It says it cannot find the `run_R.out` file, but yet it's there.  I can watch, within the `Outputs` folder, as the Platform deletes it out;  it then errs.  

I have tried running different copies of the Platform, and all end up with the same error.  When we update the R code, we update the entirety of the Platform and its folders.  So, all copies of the same version of the Platform seem to now mysteriously err in this way.  Therefore, I suspect that some condition on my computer has recently changed.  I have both "restarted" and "shut down," but neither ameliorated the issue.  Via "Installed Updates," it looks like my computer hasn't loaded anything new since 11/10/2015.

Technically, the error states that 
![image](https://cloud.githubusercontent.com/assets/9057972/12238029/13de6254-b83f-11e5-9cba-450255d56f94.png)
even though the `run_R.out` file was there.  (Although the Platform deletes it, in doing whatever it does.) 

I've attached the details that pop up when hitting the "Details" button in the graphic above.  

[Details.txt](https://github.com/tmcd82070/CAMP_RST/files/85968/Details.txt)

It should be noted that I'm using the "2014 09 23 RST VB code" of the Platform, as found within the `ftp` site.  It seems this may not be the current version, so updating may solve the issue.

**Comment by jasmyace** [comment]
Installing the new version of the Platform seemed to solve the problem.  

Trent (and maybe Jared?) will need to install the newer version of the Platform.  I placed the zip file `CAMPRST20150706.zip` containing its components in  

    \\lar-file-srv\Data\PSMFC_CampRST\ThePlatform\CAMP_RST20160201.

**Comment by jasmyace** [comment]
Unfortunately, this same error has reappeared.  Earlier today, I updated Windows because it told me to.  

When I place a `run_R.out` in the `Outputs` folder, it deletes it, and then complains about its not being there.  

Not sure what to do;  please advise.


![image](https://cloud.githubusercontent.com/assets/9057972/12406055/e8fb2b3a-be06-11e5-8ae8-63974d053780.png)


```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not find file '\\lar-file-srv\Data\PSMFC_CampRST\ThePlatform\CAMP_RST20160201\outputs\run_R.out'.
File name: '\\lar-file-srv\Data\PSMFC_CampRST\ThePlatform\CAMP_RST20160201\outputs\run_R.out'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path)
   at RST_WinFront.frmManageOutputs.cmdRunAnalysis_Click(Object sender, EventArgs e) in C:\Files\Visual Studio 2010\Projects\CAMPRST-ReducedComments\RST_WinFront\frmManageOutputs.vb:line 584
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
CAMPrst
    Assembly Version: 2015.7.6.1300
    Win32 Version: 1.2.0.0
    CodeBase: file://lar-file-srv/Data/PSMFC_CampRST/ThePlatform/CAMP_RST20160201/CAMPrst.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.VisualBasic/8.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Runtime.Remoting/2.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.VisualBasic.PowerPacks.Vs
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.30319.1
    CodeBase: file://lar-file-srv/Data/PSMFC_CampRST/ThePlatform/CAMP_RST20160201/Microsoft.VisualBasic.PowerPacks.Vs.DLL
----------------------------------------
RST_BIZ
    Assembly Version: 0.9.0.0
    Win32 Version: 0.9.0.0
    CodeBase: file://lar-file-srv/Data/PSMFC_CampRST/ThePlatform/CAMP_RST20160201/RST_BIZ.DLL
----------------------------------------
System.Data
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8677 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_32/System.Data/2.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Data.DataSetExtensions
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.30729.8693 built by: QFE
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Data.DataSetExtensions/3.5.0.0__b77a5c561934e089/System.Data.DataSetExtensions.dll
----------------------------------------
Accessibility
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Accessibility/2.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Transactions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_32/System.Transactions/2.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_32/System.EnterpriseServices/2.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by ConnieShannon** [comment]
Jason, you might try moving the application closer to the root.  Second, maybe the code to delete the table is being run twice?

Also, I've got a function that looks for a table and if it is there it deletes it and if it isn't it does 'something else'.  I'm not sure if it's vb or vba.  
[CAMP_West_v2.zip](https://github.com/tmcd82070/CAMP_RST/files/96356/CAMP_West_v2.zip)

Would you like to have a look?  Just unzip to the data folder.  The first time you open it you will need to use the link checking button at the bottom of the main form to location the CAMP.mdb. If this code plays nice you would not need to have a table in their, it will work either way.  And you can build a new one each time so we won't have the problem of missing tables.

If you give me a call I can explain how it works.  It's pretty easy to do in Access...not sure about R.
530-225-2155.

**Comment by MikeBanach** [comment]
Hi Jason,
    
    I'm not sure what you mean by "When I place a run_R.out in the
    Outputs folder ...".  Is that in your code, or are you doing it
    manually (e.g., copy/paste)?
    
    When the button is pushed to run the R routines from the user
    interface then:
    
      the file 'run_R_out.backup' in
        the outputs directory, if it exists, gets deleted.
      the file 'run_R.out' in the
        outputs directory, if it exists, is from a previous run.  It
        gets renamed 'run_R_out.backup'.
      
        (A new file named 'run_R.out'
          can then be created by your R programming.)
      
      it checks to be sure site, taxon, run, year, and time period
        are all provided.
      it creates the files needed by your R routines.
      it makes sure 'rbatch.bat'
        exists.
      it runs 'rbatch.bat'.
      it waits for 'rbatch.bat' to
        finish.
      it creates an object to read the new 'run_R.out'
        file.
      
      
        It looks like this is the line where there error is
          occurring.  And that makes no sense to me because that line
          doesn't actually do anything other than declare a variable.
        
      
    
    Possible solutions:
    
      I like Connie's idea of putting the platform in a directory
        closer to the root.  I don't think this is the problem, but it's
        worth a try and is a good first thing to test, because there are
        path and file name maximum values that have to be adhered to.
      A second thought I have is that maybe you have a computer
        that's so fast that it is exposing a timing issue in the user
        interface that is not an issue on older computers.  If so, that
        could probably be fixed with one line of code.
      When the platform is distributed, due to security reasons we
        send it out with the file 'rbatch.txt'
        rather than 'rbatch.bat'. 
        The code renames the .txt file to .bat if necessary.  So if you
        were given a copy of the platform that had '.rbatch.bat' rather than .txt, then you may be having
        security issues.  The solution is to create a new rbatch.bat
        file and copy the contents of the current one into it.  I doubt
        this is the problem but it's worth trying because it's easy.
      
      A final thought I have -- and this may sound a bit insulting
        so I apologize in advance, but I'm stumped and brainstorming --
        is that the R code is not creating the file '<<application path>>\outputs\run_R.out'. 
        Did the path or file name accidentally get changed in the R
        code?  Maybe the path was hard-coded for some test and wasn't
        changed back?  Maybe the line of code that actually writes the 'run_R.out' file was commented out or
        accidentally deleted?  Do you make your File Explorer show file
        extensions?  If not, and you see a file called "run_R.out", then it is actually "run_R.out.out" or "run_R.out.txt" or something else.
      
    
    If neither the first nor third nor fourth of those possible solution
    bullets is the problem, then zip up and send me your whole platform,
    R, R-interface, and database setup for me to test.  (There are no
    email security problems on my side, and I can receive attachments up
    to at least 55MB.  If it's bigger than that then I can send you a
    link to upload the file.)  Tell me your exact steps to produce the
    error, and send my your email address and phone number.  We'll get
    this figured out and fixed.
    
    Mike
    
    Michael Banach
StreamNet Fisheries Biologist
Pacific States Marine Fisheries Commission
503-595-3152         mike_banach@psmfc.org
www.streamnet.org

    
      
      
      On 1/18/2016 4:20 PM, Jason wrote:
    
    
      
      Unfortunately, this same error has reappeared. Earlier today, I
        updated Windows because it told me to. 
      When I place a run_R.out in the Outputs
        folder, it deletes it, and then complains about its not being
        there. 
      Not sure what to do; please advise.
      
      See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not find file '\\lar-file-srv\Data\PSMFC_CampRST\ThePlatform\CAMP_RST20160201\outputs\run_R.out'.
File name: '\\lar-file-srv\Data\PSMFC_CampRST\ThePlatform\CAMP_RST20160201\outputs\run_R.out'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path)
   at RST_WinFront.frmManageOutputs.cmdRunAnalysis_Click(Object sender, EventArgs e) in C:\Files\Visual Studio 2010\Projects\CAMPRST-ReducedComments\RST_WinFront\frmManageOutputs.vb:line 584
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
CAMPrst
    Assembly Version: 2015.7.6.1300
    Win32 Version: 1.2.0.0
    CodeBase: file://lar-file-srv/Data/PSMFC_CampRST/ThePlatform/CAMP_RST20160201/CAMPrst.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.VisualBasic/8.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Runtime.Remoting/2.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.VisualBasic.PowerPacks.Vs
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.30319.1
    CodeBase: file://lar-file-srv/Data/PSMFC_CampRST/ThePlatform/CAMP_RST20160201/Microsoft.VisualBasic.PowerPacks.Vs.DLL
----------------------------------------
RST_BIZ
    Assembly Version: 0.9.0.0
    Win32 Version: 0.9.0.0
    CodeBase: file://lar-file-srv/Data/PSMFC_CampRST/ThePlatform/CAMP_RST20160201/RST_BIZ.DLL
----------------------------------------
System.Data
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8677 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_32/System.Data/2.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Data.DataSetExtensions
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.30729.8693 built by: QFE
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Data.DataSetExtensions/3.5.0.0__b77a5c561934e089/System.Data.DataSetExtensions.dll
----------------------------------------
Accessibility
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Accessibility/2.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Transactions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_32/System.Transactions/2.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8670 (QFE.050727-8600)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_32/System.EnterpriseServices/2.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

      —
        Reply to this email directly or view
          it on GitHub.

**Comment by ConnieShannon** [comment]
If I understand what Mike said, the user interface is deleting the 'run_R.out' file.  The code you currently run expects a table to be there for it to delete however the user interface has already deleted it and so you get the same error as happens when any of the other output temp tables is missing.

There is something different and less functional about the newer R code ability to deal with existing tables.

**Comment by jasmyace** [comment]
Thanks all for the suggestions.  

I started investigating by trying to run the Platform on an older computer.  (I have previously used this older computer for testing, so I knew that historically, it had worked.)  I was surprised to find that the Platform failed on this older computer as well.  So, I concluded the issue(s) weren't related specifically to my newer computer.  

I then moved the Platform folder to `C:\`, and tried it from there.  It worked as intended.  I do not think the folder path is too long;  its length is the same as it has always been.  My guess is that the problem is due to our running the Platform from a network drive;  I have previously run up against Windows issues regarding confusion with respect to the network server name `lar-file-srv` versus its letter designation `L:\`.  

Is there something we can do to keep the Platform working on our network drive?  I'm always testing our updated R code via the Platform -- sometimes this amounts to several code runs a day.  It would be cumbersome to have to update a local copy of the Platform for each run.  We need to keep the working R code on the network drive to make sure it gets backed up.

**Comment by MikeBanach** [comment]
Jason, we’ve been down this path before and didn’t come up with a good solution.  See the emails between me and Doug below from 1/16/2013 that I copied below.

The path of least resistance, I think, is for you to make a batch file that will copy your network R-Interface files to your local C: drive and then run the platform/R code from there.  Make a desktop shortcut of the batch file and give it a hotkey.  This approach will even give you an instant backup copy.

An old DOS guy like Trent (?) or me can help you with the batch file if necessary.

Mike

Mike_banach@psmfc.org
503-595-3152



On 1/16/2013 11:03 AM, Threloff, Doug wrote:

ok.  thanks for the email.

it sounds like in most cases people will need to follow the mechansim you created for the feather river staff.  thanks for creating the batch file.  i guess robyn got lucky with a fast server connection.

have a good day.

Doug Threloff, Program Manager
Comprehensive Assessment and Monitoring Program

U.S. Fish and Wildlife Service
Sacramento Fish & Wildlife Office
2800 Cottage Way, Room W-2605
Sacramento, CA 95825
Tel: (916) 414-6726   Fax: (916) 414-6713
doug_threloff@fws.gov<mailto:doug_threloff@fws.gov>

On Wed, Jan 16, 2013 at 10:24 AM, Mike Banach <mike_banach@psmfc.org<mailto:mike_banach@psmfc.org>> wrote:
Doug,

Robyn Bilski says that she runs the program off a network drive and the performance is fine.  Gay Ann tried that and it did not work for her -- things took too long to run.

After getting off the phone with you just now I gave it whirl.  I ran the program off a network drive, where the program and the database where on the network.  For me it was not reasonable, and we have a very fast network here.  I think the performance was somewhere in between what Robyn experienced and what Gay Ann experienced, and I judge it to be impractical because the performance was too slow.  I also had trouble getting the marks button to work on the Catch form.

I tried one more experiment.  I ran the program on my computer but put the back end database on the server, and used an intermediate Access database file as an intermediary to point to the database file on the server.  This intermediary had no tables of its own, it just pointed to those on the server.  This gave me the same results as running the program off the server.  It was not practical.

So if people want their databases on the server, I think the way we have set up for the Feather River people is the way to go.  That is, we move the database file off the server and to their hard drive, then run the program locally, and then move the database file back to the server.  It seems to work well.

Mike

**Comment by ConnieShannon** [comment]
The batch file has not worked well for several programs.  We gave up the idea with the Feather program after the third time the back end database was corrupted.  The Stanislaus also gave up the batch file.   If Jason can get it to work this still might be a solution.

When you think about the concept however, the batch file brings the data to the user interface.  Instead, why not consider adding some code to the user interface that allows it to link to a camp.mdb on any drive and not just the ones found in the Data folder.  The QC application has this code and it seems to work fine for everyone.  This would be a Mike or Karen fix I think.

The advantage is that the user interface can link to a CAMP.mdb located on any drive.  The disadvantage is that Access may be of limited usefulness when two or more users try to tap into the backend database at the same time.

**Comment by jasmyace** [comment]
I moved all my historical Platforms to my local `C:\` drive for testing purposes.  It appears to work.  

If anybody has any other ancillary issues associated with this issue, please feel free to open a new issue.
