### ISSUE TITLE
Catch Query Question Based on Small Time Frame

### ISSUE THREAD

**Issue by jasmyace** [tmcd82070/CAMP_RST#67]
In investigating the American river database, as provided by Krista, I ran the data from 12/21/2001 through 7/29/2002.  I also, however, ran the data from 1/23/2002 through 3/1/2002.  I chose these dates because when I peeked in the data at the database provided to me, Connie's table `TempSumUnmarkedByTrap_Run_Final` had trap visits with this date range.  I surmised that this is the range Krista used in playing with her data.  

Krista, in her email however, indicated her interest was from 1/29/2002 through 2/25/2002.  So, I tried to query for this datarange as well;  however, the query failed.  There are two trapping instances (trapVisitID = 793 & trapVisitID = 782) that are on the cusp of this time frame, based on day.  There are no trapping instances in between these two days.  I know these are valid fishing, because they appear as such on the query run from 1/23/2002 through 3/1/2002.

![image](https://cloud.githubusercontent.com/assets/9057972/12679957/740e589a-c664-11e5-9ea3-6e5d721ba0c5.png)

But, when I run the smaller query from 1/29/2002 through 2/25/2002, I get no records in table `TempSumUnmarkedByTrap_Run_Final`;  however, query `QryBuildReportCriteria` brings back 20 records.  While we have code to stop the Platform when the number of records brought back by `QryBuildReportCriteria` is zero, we currently have nothing to stop the code when `QryBuildReportCriteria` brings back non-zero records, but the ultimate number of records in `TempSumUnmarkedByTrap_Run_Final` is zero.  Do I need to update the R code to provide for this possibility?

**Comment by ConnieShannon** [comment]
Jason the queries to generate TempSumUnmarkedByTrap_Run_Final appear to be working correctly.  When dates are selected for analysis they must begin with a start trapping record.  When the first record doesn't indicate the beginning of a trap sequence the queries treat the first visit as the start visit.  The start visit is required to identify the number of hours the trap was allowed to fish for each sample catch.
We could add some code that returns a comment however I think this is something that is generally understood by the biologists.

I think in the data are the problem here and if anything the R code could generate a comment to indicate that too few samples were available to generate a valid production estimate.  I don't know how or if that is possible.  We do not know how many samples are required to generate a valid estimate.  We don't have any minimum requirements to check the data against.

In this case when Krista added 20% more samples by setting the includeCatch to 'yes'. the 'R' application seemed to do well enough.

In the data that you got there are more imputed catch days than valid sample days.  For example, only 94 of 368 rows include “propImputed” =0.  This indicates that traps were fished successfully about 25% of the time and about 25% of those days were zero catch days.  Resetting the Include catch to 'yes' to add in 20% more samples would have resulted in about 45% of trapping season.  I think it's a pretty safe bet that at least 45% of the selected date range must have resulted in a vaid sample in order to get a valid production estimate.  If there is some way to nail that down it might be helpful.

**Comment by jasmyace** [comment]
Note that I put years of 2015 when I originally wrote this, but they should have been 2002.

Okay, just to be sure I understand. 

I think I see now.  I naively assumed that variables `visitTime` and `visitTime2` corresponded to variables `StartTime` and `EndTime` in table `TempSumUnmarkedByTrap_Run_Final`;  however, variable `StartTime` comes from variable `visitTime` of the temporally previously trapping record.  So, both `StartTime` and `EndTime` originate from `visitTime`, but from different records.  

In this case, in the trapping instance I note above, `trapVisitID = 782` corresponds to a Fishing instance that actually started on January 25th, as seen via the record associated with `trapVisitID = 781`.  Given that 1/25 is outside the requested date range of 1/29/2002 through 2/25/2002, this record isn't included.  

We currently don't have anything to handle this situation.  If Krista had tried to put in an "ALL runs" query based on the date range of 1/29/2002 through 2/25/2002, I think the code would have crashed ungracefully, since some of the interim queries bring back records, but the final table `TempSumUnmarkedByTrap_Run_Final` does not.  

I'll add something to the R `F.get.catch.data.r` function code to try and handle this situation.

**Comment by jasmyace** [comment]
Okay, I added a small bit of code to trap this instance, and then stop the code.  

An error of the following will pop up in the `run_R.out` file.  

![image](https://cloud.githubusercontent.com/assets/9057972/12683058/33612aa6-c674-11e5-8ea5-6a91009a645e.png)


Thanks for the help in quickly resolving this issue.

**Comment by ConnieShannon** [comment]
Jason can you please explain "We currently don't have anything to handle this situation. If Krista had tried to put in an "ALL runs" query based on the date range of 1/29/2002 through 2/25/2002, I think the code would have crashed ungracefully, since some of the interim queries bring back records, but the final table TempSumUnmarkedByTrap_Run_Final does not."  Why is this the case?

**Comment by jasmyace** [comment]
Because `TempSumUnmarkedByTrap_Run_Final` ends up empty, but `QryBuildReportCriteria` finds 20 records to place in table `TempReportCriteria_Trapvisit`.  The code currently only checks for records in `TempReportCriteria_Trapvisit`, which is not strong enough in this particular case.  

![image](https://cloud.githubusercontent.com/assets/9057972/12683183/0db39f54-c675-11e5-9875-fdab968432dc.png)
