### ISSUE TITLE
halfCone Operations in Estimating Efficiency

### ISSUE THREAD

**Issue by jasmyace** [tmcd82070/CAMP_RST#73]
**OVERVIEW:** Marked fish captured during efficiency trials may result from halfCone operations.  In allowing for a "times 2" adjustment in the catch sequence, it may make sense to allow the same in the efficiency sequence.  

**RESOLUTION:** Ensure that the correct efficiency recapture of fish is correct, where "correct" depends on the methodology used.  

**DETAILS:**  In dealing with something else, I observed that the data frame that results from the efficiency queries also reports halfCone status.  Up to now, we only manipulate halfCone catch after the completion of the **catch** query sequence by multiplying by 2.  No manipulation occurs following the efficiency query sequence.  

Should the recaptures that result during halfCone operations be multiplied by two as well?  I believe that the final query that brings these integer counts back (in field `Recaps` in table `TempRelRecap_final`) originate from catches that occur over time, i.e., this is a summary table, where each record of `Recaps` results from (possibly) several trapping instances over several days.  So, should these final numbers be multiplied by two, should constituent data that make up these final `Recaps` numbers (sometimes) be mulitplied by two, or should nothing happen at all?  (Note that if these data do result from several trapping instances, does a `halfCone == Yes` in table `TempRelRecap_final` mean that all the traps that make up a particular `Recaps` numerator were operating during halfCone operations, or was it just one?)

**Example**
The table below results from the RBDD, following a call for the lifeStage passage report, 12/1/2005 - 11/30/2006.

In consideration of the questions above, should the 6 `Recaps` in the figure below be a 12?  Is it the case that this 6 results from several trapping instances that take place during that week of waiting for the release to get to a trap(s)?  If so, did all those trapping instances work under halfCone operations, or was it just one?  Or, is everything okay, and nothing needs to be done?  

![image](https://cloud.githubusercontent.com/assets/9057972/13751223/c1c6cd8c-e9ce-11e5-8649-f014c64ebd1b.png)
  
Do we need to adjust this?  (Or did you assume I already manipulated these numbers by 2?)

**Comment by tmcd82070** [comment]
Jason,

It is my opinion that we need to multiply the efficiency fish caught during
1/2 cone operations by 2.  Perhaps the more advanced efficiency models we
plan to implement later will make this adjustment unnecessary, but for now,
it makes logical sense to do it (i.e., multiply number recaptured by 2 --
do not multiply number released by 2).

Trent

*-------------------------------------------------------*
*Trent McDonald, PhD *
*Senior Statistician*


Environmental & Statistical Consultants
200 S. Second Street
Laramie, WY 82070
(307) 721-3172
(307) 760-4721 Cell
Publications: Google Scholar
<https://scholar.google.com/citations?user=K1031qoAAAAJ&hl=en>, ResearchGate
<https://www.researchgate.net/profile/Trent_Mcdonald>
tmcdonald@west-inc.com
www.west-inc.com

*Follow WEST: *Facebook
<http://www.facebook.com/pages/Western%E2%80%90EcoSystems%E2%80%90Technology%E2%80%90WESTInc/125604770807646>
, Twitter <http://twitter.com/WestEcoSystems>, Linked In
<http://www.linkedin.com/company/1458419>, Join our Mailing list
<http://visitor.r20.constantcontact.com/manage/optin/ea?v=001qrD4A3S5xJ5KgMyelH9jyw%3D%3D>

CONFIDENTIALITY NOTICE:  This message and any accompanying communications
are covered by the Electronic Communications Privacy Act, 18 U.S.C. §§
2510-2521, and contain information that is privileged, confidential or
otherwise protected from disclosure.  If you are not the intended recipient
or an agent responsible for delivering the communication to the intended
recipient, you are hereby notified that you have received this
communication in error.  Dissemination, distribution or copying of this
e-mail or the information herein by anyone other than the intended
recipient, or an employee or agent responsible for delivering the message
to the intended recipient, is prohibited.  If you have received this
communication in error, please notify us immediately by e-mail and delete
the original message.  Thank you.

P Please consider the environment before printing.

**Comment by dougthreloff** [comment]
Trent:  I agree with your suggestion below, i.e., we need to multiply the
recaptured marked trap efficiency salmon caught during 1/2 cone operations
by 2.



Doug



*From:* Trent [mailto:notifications@github.com]
*Sent:* Monday, March 14, 2016 4:45 PM
*To:* tmcd82070/CAMP_RST
*Subject:* Re: [CAMP_RST] halfCone Operations in Estimating Efficiency (#73)



Jason,

It is my opinion that we need to multiply the efficiency fish caught during
1/2 cone operations by 2. Perhaps the more advanced efficiency models we
plan to implement later will make this adjustment unnecessary, but for now,
it makes logical sense to do it (i.e., multiply number recaptured by 2 --
do not multiply number released by 2).

Trent

*-------------------------------------------------------*
*Trent McDonald, PhD *
*Senior Statistician*


Environmental & Statistical Consultants
200 S. Second Street
Laramie, WY 82070
(307) 721-3172
(307) 760-4721 Cell
Publications: Google Scholar
<https://scholar.google.com/citations?user=K1031qoAAAAJ&hl=en>, ResearchGate
<https://www.researchgate.net/profile/Trent_Mcdonald>
tmcdonald@west-inc.com
www.west-inc.com

*Follow WEST: *Facebook
<
http://www.facebook.com/pages/Western%E2%80%90EcoSystems%E2%80%90Technology%E2%80%90WESTInc/125604770807646
>
, Twitter <http://twitter.com/WestEcoSystems>, Linked In
<http://www.linkedin.com/company/1458419>, Join our Mailing list
<
http://visitor.r20.constantcontact.com/manage/optin/ea?v=001qrD4A3S5xJ5KgMyelH9jyw%3D%3D
>

CONFIDENTIALITY NOTICE: This message and any accompanying communications
are covered by the Electronic Communications Privacy Act, 18 U.S.C. §§
2510-2521, and contain information that is privileged, confidential or
otherwise protected from disclosure. If you are not the intended recipient
or an agent responsible for delivering the communication to the intended
recipient, you are hereby notified that you have received this
communication in error. Dissemination, distribution or copying of this
e-mail or the information herein by anyone other than the intended
recipient, or an employee or agent responsible for delivering the message
to the intended recipient, is prohibited. If you have received this
communication in error, please notify us immediately by e-mail and delete
the original message. Thank you.

P Please consider the environment before printing.


On Mon, Mar 14, 2016 at 10:35 AM, Jason <notifications@github.com> wrote:

> OVERVIEW: Marked fish captured during efficiency trials may result from
> halfCone operations. In allowing for a "times 2" adjustment in the catch
> sequence, it may make sense to allow the same in the efficiency sequence.
>
> RESOLUTION: Ensure that the correct efficiency recapture of fish is
> correct, where "correct" depends on the methodology used.
>
> DETAILS: In dealing with something else, I observed that the data frame
> that results from the efficiency queries also reports halfCone status. Up
> to now, we only manipulate halfCone catch after the completion of the
> *catch* query sequence by multiplying by 2. No manipulation occurs
> following the efficiency query sequence.
>
> Should the recaptures that result during halfCone operations be multiplied
> by two as well? I believe that the final query that brings these integer
> counts back (in field Recaps in table TempRelRecap_final) originate from
> catches that occur over time, i.e., this is a summary table, where each
> record of Recaps results from (possibly) several trapping instances over
> several days. So, should these final numbers be multiplied by two, should
> constituent data that make up these final Recaps numbers (sometimes) be
> mulitplied by two, or should nothing happen at all? (Note that if these
> data do result from several trapping instances, does a halfCone == Yes in
> table TempRelRecap_final mean that all the traps that make up a
> particular Recaps numerator were operating during halfCone operations, or
> was it just one?)
>
> *Example*
> The table below results from the RBDD, following a call for the lifeStage
> passage report, 12/1/2005 - 11/30/2006.
>
> In consideration of the questions above, should the 6 Recaps in the
> figure below be a 12? Is it the case that this 6 results from several
> trapping instances that take place during that week of waiting for the
> release to get to a trap(s)? If so, did all those trapping instances work
> under halfCone operations, or was it just one? Or, is everything okay, and
> nothing needs to be done?
>
> [image: image]
> <
https://cloud.githubusercontent.com/assets/9057972/13751223/c1c6cd8c-e9ce-11e5-8649-f014c64ebd1b.png
>
>
> Do we need to adjust this? (Or did you assume I already manipulated these
> numbers by 2?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tmcd82070/CAMP_RST/issues/73>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/tmcd82070/CAMP_RST/issues/73#issuecomment-196573150>.[image:
Image removed by sender.]

**Comment by jasmyace** [comment]
Connie, I believe that query 2. in `QryEfficiencyTests.sql` needs to have some type of modification so that when you sum field `CatchRaw.n` over various trapping instances, those `CatchRaw.n` values are selectively multiplied by 2, depending on if the summands that make up `CatchRaw.n` were from halfCone trapping operations.

In terms of the example above, simply multiplying by 2 may not be correct, if only one of the fish captured was captured during a halfCone trapping instance, say, of five trapping instances total.  (So, the other four trapping instances were during fullCone operations.)  In this case, I think that the correct number of recaptures would be 7, and not 6, nor 12.  

What do you think?

**Comment by ConnieShannon** [comment]
The TempRelRecap_final table contains the summarized results of efficiency tests by trap visit.  Two fields, nReleased and Recaps contain the information used to calculate the trap efficiency at the trapVisit scale (e.g., there may be several trapVisits with recaps associated with the same release.)  This trap visit level summary is where you will want to double the number of Recaps when the HalfCone field is Yes.  Afterwards all of the recaps can be added together for each trap and for each test so that the efficiency can be calculated to include any adjustements for HalfCone use.

If you like, I can modify the sql and double the recaps for you.  I would build a new version of the TempRelRecap_final table so that it would clearly indicate that the recaps were doubled.  If you would like my help just let me know.  530-225-2155

**Comment by jasmyace** [comment]
I see now.  I assumed that Trent just read in the table that results from the query.  In reality, he manipulates it somewhat prior to use.  I have added logic to function `get_release_data.R` so as to expand the number of recaptures, via variable `Recap` by an expansion factor.  In this case, the expansion factor is 2.

Also, note that I added the "2" factor as global variable `halfConeMulti` in the `source` file.  In this way, one could easily adapt a value of 1.9, or 2.1, or whatever, if desired.  This could be useful for future sensitivity analyses.  

Finally, note that I will have to take a look at the Summarize Releases report before I can close this issue; i.e., I will probably need to add a `halfConeAdj` variable to the `csv` output that results from that report, so as to not mislead end-users.

**Comment by jasmyace** [comment]
This update has been implemented, and the Big Looper run over the RBDD, in order to quantify the effects of this change.  These are below in red.  Keep in mind that the columns, in any one color, are in the order of passage / lower confidence limit / upper confidence limit.  

![image](https://cloud.githubusercontent.com/assets/9057972/13853877/6c5fb25c-ec2e-11e5-8add-64e54f07fe5e.png)


The years in which halfCone operations were prevalent are obvious, i.e., passage changed substantially.  I checked a couple of estimated efficiencies by comparing Connie's table `TempRelRecap_final` against the `csv` output for efficiency from the R programs.  This basically means I compared the "what-goes-in" against the "what-comes-out," in terms of efficiency.  Here is an example for Gate 6.  Note how some of the numerator efficiencies are multipled by two (see the column `HalfCone` in Connie's table), but some are not.  

![image](https://cloud.githubusercontent.com/assets/9057972/13853202/56326f2c-ec2b-11e5-940b-2d9a718a65c2.png)

So, in other words, it appears that this update to efficiencies is working as intended.  

**ASIDE:**  I find that generally, the efficiencies on this river are very low.  This means that capturing a few extra fish leads to large changes in estimated efficiencies, i.e., variability, over all the efficiency trials for a trapPosition.  This large variability tends to lead to intercept-only models (horizontal lines) as the efficiency model of best-fit.  It will be interesting to see how the enhanced efficiency models handle the efficiencies on this river.  During the development of enhanced efficiency models, we will need to keep an eye on if small changes in the halfCone multiplier (say 1.9 and 2.1) lead to large changes in passage.  If so, we may need to be smarter about how we come up with the halfCone multiplier.

**Comment by jasmyace** [comment]
In running the Big Looper, I discovered a minor error when I join together the efficiency and catch estimates.  In dealing with the new decimal trapPositionIDs, I assumed that all trap IDs were of length 5.  This means that for some rivers, e.g., the Feather, a trap ID of the form "1234" (as character) from efficiency estimates was joining with "1234." from catch estimates, where the decimal originated from the use of decimal trap IDs.  The presence of the decimal was causing a mismatch, and thus many traps were not seeing the efficiencies that they should.  This in turn led to severely low estimates of passage, from which the problem was diagnosed.  

I fixed this to allow for the appropriate number of positions, which seems to always be either 4 or 5.

**Comment by ConnieShannon** [comment]
I don't think you can count on trap positions to be a certain length.

Originally the trap position is a long integer field.  This is the case in the efficiency data as well as the catch data.  In order to add the decimals I had to change the field properties from long integer to double.
 
I think the reason there is a mismatch is because the field properties for the modified trap positions had to be changed to "double" to contain the decimal numbers and the Efficiency test data is looking for a long integer field.  

If those modified trap positions are put into a long integer field then the decimals will automatically be rounded right?  There should not be a case where rounding the decimals affects the trap position ID, at least, not when the analysis is run on a single year.

Call if you think this isn't going to work or you'd like some help on my end.

**Comment by jasmyace** [comment]
We should be good to go on any issues having to do with variable lengths of `trapPositionID`s.  

I updated the Summarize Releases report to ensure that the "times 2" accounting for efficiency is recorded there as well.  Based on the river information above, the `csv` output looks like the following. 

Note that there is now a `HalfCone` column, an `nFishRecaps` column, and an `nHalfConeRecaps` column.  The `HalfCone` column tells if the trapping(s) was from halfCone operations.  This comes from Connie's query results.  The sum of the `nFishRecaps` and `nHalfConeRecaps` equals `nRecaps`.  Hopefully this nomenclature communicates what the columns actually display.  Let me know if you want something changed. 

![image](https://cloud.githubusercontent.com/assets/9057972/14023104/70821490-f1a8-11e5-9baa-6225326da093.png)
