### ISSUE TITLE
Sunrise and Sunset in Catch Spline Models

### ISSUE THREAD

**Issue by jasmyace** [tmcd82070/CAMP_RST#75]
**OVERVIEW:** The catch spline models originally developed utilized a constant sunrise of 7:00 AM and a sunset of 7:00 PM for all days.  These variables are used to formulate a night-time indicator variable in catch spline models.  However, the "Dates" table developed by Connie (and most recently amended for the use of custom Julian weeks) contains daily sunrises and sunsets.  

**QUESTION:**  Should the catch spline models be enhanced to utilize the more correct and readily available sunrises and sunsets, in lieu of a constant sunrise and sunset of 7 AM and 7 PM, respectively?  I estimate this enhancement would take around one half-hour to one hour of time.

**Comment by dougthreloff** [comment]
Jason:



My sense is that the batch date runs from 2 AM to 2 AM.  I’m not sure if
the code was ever built to impute day and night time catches, although that
is something that Trent and I talked about doing.  If Trent thinks the
budget will accommodate the change in the sunrise-sunset times, then yes
please modify the code.  If he thinks were are too far into a budget hole,
that revision to the R code can wait until later.



Doug





*From:* Jason [mailto:notifications@github.com]
*Sent:* Tuesday, March 15, 2016 2:39 PM
*To:* tmcd82070/CAMP_RST
*Subject:* [CAMP_RST] Sunrise and Sunset in Catch Spline Models (#75)



OVERVIEW: The catch spline models originally developed utilized a constant
sunrise of 7:00 AM and a sunset of 7:00 PM for all days. These variables
are used to formulate a night-time indicator variable in catch spline
models. However, the "Dates" table developed by Connie (and most recently
amended for the use of custom Julian weeks) contains daily sunrises and
sunsets.

QUESTION: Should the catch spline models be enhanced to utilize the more
correct and readily available sunrises and sunsets, in lieu of a constant
sunrise and sunset of 7 AM and 7 PM, respectively? I estimate this
enhancement would take around one half-hour to one hour of time.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/tmcd82070/CAMP_RST/issues/75>[image: Image removed by
sender.]

**Comment by jasmyace** [comment]
Let's keep in mind that this would be a nice addition to have at some later date.  For now, however, I'm closing the Issue.
