### ISSUE TITLE
Sacramento (RBDD) -- Comparison of Passage Estimates in Preparation for Release 4.5

### ISSUE THREAD

**Issue by jasmyace** [tmcd82070/CAMP_RST#79]
**OVERVIEW:** Buy-in of outside users of the Platform will be enhanced if the passage estimates that result agree with expectation.  

**RESOLUTION:** Compare results easily obtained, via the Big Looper checking process, with externally obtained results.  

**DETAILS:**  Take the Fall passage estimates from year ALL runs reporting and compare to external sources.  For the Sacramento (RBDD) river, these numbers utilize database `CAMP_RBDD_19June20151` of approximately 552,356 KB in size.  

The Fall passage estimates utilized here follow.  Keep in mind that column `bEst` is the estimate of passage, while columns `bLCL` and `bUCL` are the 95% confidence bounds.  

![image](https://cloud.githubusercontent.com/assets/9057972/13888769/dafa5d68-ed08-11e5-9cdf-c0b82d7b1d9b.png)

Do these align with expectation?  Keep in mind that the large estimate of passage here in year 2005 is due to an estimated efficiency of zero.

**Comment by dougthreloff** [comment]
Jason:



I have developed the attached spreadsheet that compares the Red Bluff
Diversion Dam (RBDD) fall-run Chinook salmon numbers that were developed
by: (a) the CAMP RST Platform, and (b) the biologist that supervises the
rotary screw traps at that site.



There are some marked differences in the two sets of numbers.  We will need
to explore why the numbers are markedly different in some years, and be
able to point to specific reasons why the numbers differ.  Two obvious
explanations for the differences in the two sets of numbers:  (1) the
multi-year trap efficiency model used by the RBDD biologists, and (2) the
RBDD trap efficiency model that uses % of river discharge sampled by the
RSTs as a way of estimating trap efficiency.  If we are going to say these
are the reasons the two sets of numbers differ, we will need to be able to
identify specific cases supporting that explanation.



Doug



*From:* Jason [mailto:notifications@github.com]
*Sent:* Friday, March 18, 2016 1:04 PM
*To:* tmcd82070/CAMP_RST
*Subject:* [CAMP_RST] Sacramento (RBDD) Comparison of Passage Estimates in
Preparation for Release 4.5 (#79)



*OVERVIEW:* Buy-in of outside users of the Platform will be enhanced if the
passage estimates that result agree with expectation.

*RESOLUTION:* Compare results easily obtained, via the Big Looper checking
process, with externally obtained results.

*DETAILS:* Take the Fall passage estimates from year ALL runs reporting and
compare to external sources. For the Sacramento (RBDD) river, these numbers
utilize database CAMP_RBDD_19June20151 of approximately 552,356 KB in size.

The Fall passage estimates utilized here follow. Keep in mind that column
bEst is the estimate of passage, while columns bLCL and bUCL are the 95%
confidence bounds.

[image: Image removed by sender. image]
<https://cloud.githubusercontent.com/assets/9057972/13888769/dafa5d68-ed08-11e5-9cdf-c0b82d7b1d9b.png>

Do these align with expectation? Keep in mind that the large estimate of
passage here in year 2005 is due to an estimated efficiency of zero.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/tmcd82070/CAMP_RST/issues/79>[image: Image removed by
sender.]

**Comment by jasmyace** [comment]
1. Can you send me the spreadsheet directly?  It seems that attachments to the GitHub email system aren't supported, i.e., it didn't make it to GitHub.  I'll then add it directly here (to GitHub).  

2. Since it seems that both of these (potential) explanations are tied to efficiency, and we will be spending a decent amount of time on modifying efficiency, it would be efficient (heh) if we wait to investigate these comparisons once we are neck-deep in modifying the efficiency models.  When we start to develop the efficiency models, we could choose to start the modifications / investigations with one of the RBDD fall-run years, in order to solve both the updated efficiency models, as well as the comparison investigations, at the same time.

**Comment by jasmyace** [comment]
(from Doug)

  1. See attached file.  I always wondered how Github added (or did not add) an attached file.  I think we talked about this once before? If your  other Github posting have annual fall-run Chinook salmon production estimate tables like the one for Red Bluff Diversion Dam (and I think they do), I will send you tables like the one attached to this email for other watersheds, e.g., Stanislaus River – Caswell State Park and Feather River.  

  [difference between Poytress and CAMP Platfrom numbers.xlsx](https://github.com/tmcd82070/CAMP_RST/files/192075/difference.between.Poytress.and.CAMP.Platfrom.numbers.xlsx)

  2. I agree we should wait to investigate the comparisons once we are neck-deep in modifying the efficiency models.  Off the top of my head, I can’t think of a more efficient way to conduct an investigate that would explain the differences in the numbers coming from the CAMP vs. Red Bluff Diversion Dam platforms.

**Comment by jasmyace** [comment]
Calculation methodologies have changed slightly, precluding accurate use of the data in this Issue.  So, I'm closing the Issue.  For the RBDD, comparisons are probably not worthwhile without the enhanced efficiency models anyway.

**Comment by jasmyace** [comment]
The Big Looper 2.0 has tentatively completed its runs for the release of R package `campR` 1.0.0.  We have made *many* changes since we last looked at numbers, so I thought I would do some superficial spot checking against numbers from the last release.  I could spend *hours* comparing and contrasting.  

Note that these numbers reflect the Fall run from the All Runs report.  You may need to go to the original Issue online to be able to compare the screenshots from before and now.  

A screenshot comparable to the above follows.  

![image](https://cloud.githubusercontent.com/assets/9057972/19932385/9b28f2a4-a0d5-11e6-99f6-3bff6d03de29.png)

Generally, most passage estimates appear in line.  Note that this screenshot does not have numbers for 2003.  It looks like the efficiency curve this time around suffers from a parallel phenomenon to that of the gaps in fishing inherent to catch.  

![image](https://cloud.githubusercontent.com/assets/9057972/19932765/ca348c92-a0d6-11e6-8f8a-175d9dbcf201.png)

Here, the efficiency curve for "hot pink" (not listed in the legend) spikes, dips, and then spikes again.  Note the scaling of the *y*-axis.  The dip dives in so close to zero that the `R` programs end up rounding the efficiency for several days down to 0.0000.  This leads to estimates of passage ballooning, and so passage for this year gets out of control.  Since we are gearing up to deal with efficiency specifically for this river, I simply note this behavior, and remove it from comparisons.
